# Generated by Django 5.0 on 2023-12-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_tarefa', models.CharField(max_length=200)),
                ('st_status', models.CharField(max_length=1)),
                ('dt_inclusao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='data cadastro')),
                ('dt_alteracao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='data alteracao')),
            ],
        ),
    ]
